### ISSUE TITLE
Chats are saved line per line

### ISSUE THREAD

**Issue by nsauwen** [ZeXtras/openchat-zimlet#3]
Chat sessions are normally saved per conversation. This morning it seems like there was an update related to chat. Since then, every line in a chat is stored as a separate item, instead of one item per conversation. Thanks for looking into this.

**Comment by tverbeke** [comment]
The Chats folder indeed saves chat sessions using one single message per line in a chat (instead of one message for the full conversation); this is using Zimbra Community Edition 8.8.6 on Ubuntu 14.04 LTS with OpenChat version 16.44.0 (https://github.com/ZeXtras/openchat-zimlet/tree/85864d0). Any other relevant information we can provide? Can you reproduce this bug?

**Comment by bud-mo** [comment]
Hello @nsauwen Thank You for Your reporting, You found a bug!
We patched the extension in order to resolve this issue, the patch will be delivered soon on Zimbra Community Edition, remember to keep Your system updated ;)

Have a nice day.
